### PR TITLE
Dynamic `Int` generation + integer primitive fixes

### LINKED ISSUE #55: int type conditional generation
The `int` type needs some work done on it. it is hard-coded right now but we need it to have different traits implemented depending on feature flags passed. There is also no wasm wrapper around it and it does not preserve its encodings. I'm partway through transitioning it to be codegenerated instead of static and implementing those things.

### LINKED ISSUE #57: nints / bools compile errors
As of the fixes in #53 `babbage.cddl` now runs through codegen, but there are various compile errors still existing relating to the above types:

1) bool::deserialize() error (likely easy to fix - might only be with preserve-encodings)
2) 5577 | ...                   Ok(x, enc) => (x as i64, Some(enc)),
             |                          ^  ^^^ expected 1 field, found 2
       and
5304 | ...   serializer.write_negative_integer_sz(*value as i128, fit_sz(*value as i128, key_9_value_value_encoding, force_canonical))?;
     |                                                                   ^^^^^^^^^^^^^^ expected `u64`, found `i128`
     both look like it's an issue with negative ints with preserve-encodings=true

### PR DESCRIPTION
**Pull request by rooooooooob**
Previously the `Int` struct was statically defined. This causes issues
because some traits, wrappers, etc are only needed for certain runtime
configurations (e.g. preserve-encodings) or usages (e.g. if it's used as a key).

This also introduces more functionality like a wasm wrapper again and
conversion traits.

Also addresses issues with other primitive types e.g. i8, i64, u8, etc
and adds unit tests to cover all of them. (signed int deserialization was fundamentally broken and certain precisions for both signed and unsigned would lead to compile errors)

Fixes #55
Fixes #57

### CODE REVIEW

File: tests/core/tests.rs [hunk 1]
```diff
@@ -118,4 +118,13 @@ mod tests {
         assert_eq!(0u64, U64::from(0u64));
         assert_eq!(0i64, I64::from(0i64));
     }
+
+    #[test]
+    fn signed_ints() {
+        // the + 1 is due to a bug in cbor_event that doesn't cover the entire range of i64
```
Comment (SebastienGllmt) [inline tests/core/tests.rs:124]: Probably best to create an issue about this in the cbor_event repo and then link to the issue in this comment

File: src/generation.rs [hunk 2]
```diff
@@ -3511,4 +3541,142 @@ fn add_struct_derives<T: DataType>(data_type: &mut T, used_in_key: bool, is_enum
             }
         }
     }
+}
+
+fn generate_int(gen_scope: &mut GenerationScope, types: &IntermediateTypes) {
+    let ident = RustIdent::new(CDDLIdent::new("int"));
+    // todo: wasm bindings + to/from string traits
```
Comment (SebastienGllmt) [inline src/generation.rs:3548]: todo? If this is meant to be done in a separate PR, let's create an issue for it and then link the issue from the comment

File: src/generation.rs [hunk 3]
```diff
@@ -3511,4 +3541,142 @@ fn add_struct_derives<T: DataType>(data_type: &mut T, used_in_key: bool, is_enum
...
+    if CLI_ARGS.wasm {
+        let mut wrapper = create_base_wasm_wrapper(gen_scope, &ident, true);
+        let mut wasm_new = codegen::Function::new("new");
+        let mut new_if = codegen::Block::new("if x >= 0");
+        new_if.line("Self(core::Int::Uint(x as u64))");
+        let mut new_else = codegen::Block::new("else");
+        new_else.line("Self(core::Int::Nint((x + 1).abs() as u64))");
```
Comment (SebastienGllmt) [inline src/generation.rs:3555]: we have +1 in a few places. Are these also all the cbor_event issue?

File: src/generation.rs (hunk 2 above)
Comment (rooooooooob) [reply src/generation.rs:3548]: Oops. I forgot to remove this comment. They're implemented in this PR.

File: src/generation.rs (hunk 3 above)
Comment (rooooooooob) [reply src/generation.rs:3555]: Probably not? The cbor_event issue is just that `i64::MIN` isn't supported (it panics). There are other +1 and -1s with handling `nint` in CBOR as those start at -1 instead of 0 like with `uint`. Even just as an API restriction in cbor_event we can't get half the range of `nint` in general. With `preserve-encodings=true` we don't have any of these issues. It's possible we could use that API for all negative integers in the `preserve-encodings=false` with some extra work to calculate the encoding explicitly.

**Comment by rooooooooob** [comment]
I stuck a couple more fixes to this PR and removed that todo. Everything in babbage.cddl seems to work now.

**Comment by SebastienGllmt** [comment]
Awesome! Can we create the issue in https://github.com/primetype/cbor_event so we can refer to it in our code and then merge this PR?

**Comment by rooooooooob** [comment]
I decided I might as well just use the explicit encoding endpoints even when `preserve-encodings=false`. That way when we generate CIP25 again without caring about encodings, we'll still be able to handle 100% of metadata, especially since this didn't throw, but instead panicked. I also added full `nint` support as we didn't handle deserializing negative constants nor did we support the full range (i.e. below `i64::MIN`) for `nint`s.

I made the issue anyway though to document this in `cbor_event`: primetype/cbor_event#9

I also had forgotten to store the encoding fields on the new `Int` struct so that's included too in that last commit.
