### PR TITLE
Fix issue with overlapping inlined basic embedded enums

### LINKED ISSUE #229: Mixed multi-field/single-field basic group enum generates non-compiling code
```cddl
non_overlap_basic_embed_mixed = [
  ; @name first
  x: uint, tag: 0 //
  ; @name second
  y: text, z: uint
]
```

### LINKED ISSUE #230: @name with explicit basic group in group choice generates non-compiling code
```cddl
basic = (text, uint)

choice = [
  ; @name foo
  basic //
  ; @name bar
  uint, basic
]
```

will generate `Self::Foo(Foo::new(...))` instead of `Self::Foo(Basic::new(...))` which won't compile as there is no struct `Foo`, only the enum variant.

The second case `Bar` works as intended as would `Foo` if it were defined inline or if @name was not used.

### LINKED ISSUE #231: Tagged basic group in enum generates non-compiling code in WASM
```
third = (bytes, uint)

third_arr = [third]

tagged_third = #6.11(third)

non_overlap_basic_not_basic = [
  third //
  third_arr //
  tagged_third
]
```

It passes the args to `Third::new()` in directly to `NonOverlapBasicNotBasic::new_tagged_third()` in wasm.

It's going to be a good idea to test tagged things more in depth in other places too.

### LINKED ISSUE #232: Non-overlapping group choice with additional encoding does not generate valid deserialization code with `--preserve-encodings=true`
with `--preserve-encodings=true`
```
non_overlap_basic_not_basic = [
  ; @name group
  basic //
  ; @name group_arr
  basic_arr //
  ; @name group_tagged
  #6.11(basic) //
  ; @name group_bytes
  bytes .cbor basic
]
```

All encoding details such as `len_encoding` (for outer array) or the tag/bytes encodings for the last two variants are not handled during deserialization. The code will not compile and they are completely not handled.

This works correctly in the regular (overlapping cbor-types i.e. brute-force try-all-variants) deserialization logic.

### PR DESCRIPTION
**Pull request by rooooooooob**
Caused when the inlining would made cddl-codegen think that the types were not overlapping since it was looking at the stored type not the actual starting cbor type (e.g. when it was a fixed value).

This would cause a problem as the type matching introduced in #199 but only in very specific cases with basic groups starting with fixed values.

Various other fixes + more test cases:

Fixes #229
Fixes #230 
Fixes #231 
Fixes #232

### CODE REVIEW

**Comment by rooooooooob** [comment]
This one isn't related to the plutus datum tool but it's been open for a while. One of the issues fixes an issue with CML re-generation for the Nonce type which was that block that wasn't parsing last month.

File: src/generation.rs [hunk 1]
```diff
@@ -6869,46 +6877,72 @@ fn generate_enum(
...
-                                .content
-                                .line(&format!("Ok({}::{})", name, variant.name));
+                        if let Some(r) = rep {
+                            let len_info = match ty.conceptual_type.resolve_alias_shallow() {
+                                ConceptualRustType::Rust(ident) if types.is_plain_group(ident) => {
+                                    types.rust_struct(ident).unwrap().cbor_len_info(types)
+                                }
+                                _ => RustStructCBORLen::Fixed(1),
+                            };
+                            // this will never be 1 line to don't bother with the below cases
```
Comment (SebastienGllmt) [inline src/generation.rs:6902]: not sure I understand what this comment means. Maybe `to` was meant to be `so`?

File: src/intermediate.rs [hunk 2]
```diff
@@ -1310,6 +1310,7 @@ impl RustType {
                 }],
                 ConceptualRustType::Primitive(p) => p.cbor_types(),
                 ConceptualRustType::Rust(ident) => {
+                    eprintln!("{ident:?}");
```
Comment (SebastienGllmt) [inline src/intermediate.rs:1313]: Did you mean to leave in these two `eprintln`?

**Review by SebastienGllmt — APPROVED** [review]

File: src/intermediate.rs (hunk 2 above)
Comment (rooooooooob) [reply src/intermediate.rs]: Removed

File: src/generation.rs (hunk 1 above)
Comment (rooooooooob) [reply src/generation.rs]: Yes. Fixed.
